name: Keycloak | Veracode CI

on:
  push:
    branches: [ "roan-branch" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "roan-branch" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: cache-1-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-1-${{ runner.os }}-m2

      - name: Build Keycloak
        run: |
           mvn clean install -nsu -B -e -DskipTests -Pquarkus,distribution
           mvn clean install -nsu -B -e -f testsuite/integration-arquillian/servers/auth-server -Pauth-server-quarkus
           mvn clean install -nsu -B -e -f testsuite/integration-arquillian/servers/auth-server -Pauth-server-wildfly
           mvn clean install -nsu -B -e -f testsuite/integration-arquillian/servers/auth-server -Pauth-server-undertow

      - name: Store Keycloak artifacts
        id: store-keycloak
        uses: actions/upload-artifact@v2
        with:
          name: keycloak-artifacts.zip
          retention-days: 2
          path: |
            ~/.m2/repository/org/keycloak
            !~/.m2/repository/org/keycloak/**/*.tar.gz

      # Download built artifacts
      - name: Download built keycloak
        id: download-keycloak
        uses: actions/download-artifact@v2
        with:
          path: ~/.m2/repository/org/keycloak/
          name: keycloak-artifacts.zip

      # Listing the folder contents is very handy for troubleshooting      
      - name: List folder contents for visual to confirm artifact file exists
        run: |
         ls -la
         la -la ~/.m2/repository/org/keycloak/

      # - name: Veracode Upload and Scan Action Step
      #   uses: veracode/veracode-uploadandscan-action@master
      #   id: upload_and_scan
      #   with:
      #     appname: 'Keycloak-Java-GitHub'
      #     createprofile: true
      #     version: '${{ github.run_id }}'
      #     criticality: Medium
      #     filepath: keycloak-artifacts.zip
      #     vid: '${{ secrets.VERACODE_API_ID }}'
      #     vkey: '${{ secrets.VERACODE_API_KEY }}'
      #   continue-on-error: true
